# Generated by Django 5.0.7 on 2024-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='account_number',
            field=models.CharField(max_length=14),
        ),
    ]
